#!/usr/bin/python
import ibquery, requests
ib = ibquery.InfoBeamerQuery("127.0.0.1")
stream = ib.node('nested/child/feebar').io(raw=False)

while True:
    print(stream[event])
    # to keep on running
