#!/usr/bin/python
# -*- coding: utf-8 -*-
from hosted import device, node, config, json, os, sys, requests, config, requests
import ibquery
ib = ibquery.InfoBeamerQuery()
s = ib.node('root/proof-of-play').io(raw=True)
print s.readline()
print config.metadata[‘device_id’]
